// Yes this was generated by AI, I value my time too much to write this out by hand...
export function validateEmailManually(email: string): boolean {
  if (email.length === 0) {
    return false
  }

  let atIndex: number = -1
  let lastDotIndex: number = -1

  // 1. Locate the '@' symbol
  // The regex implies exactly one '@' because the local and domain character sets exclude it.
  for (let i = 0; i < email.length; i++) {
    if (email[i] === '@') {
      if (atIndex !== -1) return false // Fail if multiple '@' symbols exist
      atIndex = i
    }
  }

  // Fail if there is no '@' or if it is at the very beginning (local part must be 1+ chars)
  if (atIndex === -1 || atIndex === 0) {
    return false
  }

  // 2. Validate the Local Part: ^[A-Za-z0-9._%+-]+
  const localPart: string = email.substring(0, atIndex)
  for (let i = 0; i < localPart.length; i++) {
    const charCode: number = localPart.charCodeAt(i)
    const isValid: boolean
      = (charCode >= 65 && charCode <= 90) // A-Z
        || (charCode >= 97 && charCode <= 122) // a-z
        || (charCode >= 48 && charCode <= 57) // 0-9
        || charCode === 46 // .
        || charCode === 95 // _
        || charCode === 37 // %
        || charCode === 43 // +
        || charCode === 45 // -

    if (!isValid) return false
  }

  // 3. Locate the last '.' after the '@' for the TLD separation
  for (let i = email.length - 1; i > atIndex; i--) {
    if (email[i] === '.') {
      lastDotIndex = i
      break
    }
  }

  // Fail if no dot exists after the '@', or if there's no domain part before it
  if (lastDotIndex === -1 || lastDotIndex === atIndex + 1) {
    return false
  }

  // 4. Validate the Domain Part: [A-Za-z0-9.-]+
  const domainPart: string = email.substring(atIndex + 1, lastDotIndex)
  for (let i = 0; i < domainPart.length; i++) {
    const charCode: number = domainPart.charCodeAt(i)
    const isValid: boolean
      = (charCode >= 65 && charCode <= 90) // A-Z
        || (charCode >= 97 && charCode <= 122) // a-z
        || (charCode >= 48 && charCode <= 57) // 0-9
        || charCode === 46 // .
        || charCode === 45 // -

    if (!isValid) return false
  }

  // 5. Validate the Top-Level Domain (TLD): [A-Za-z]{2,}$
  const tldPart: string = email.substring(lastDotIndex + 1)
  if (tldPart.length < 2) {
    return false // Must be at least 2 characters long
  }

  for (let i = 0; i < tldPart.length; i++) {
    const charCode: number = tldPart.charCodeAt(i)
    const isValid: boolean
      = (charCode >= 65 && charCode <= 90) // A-Z
        || (charCode >= 97 && charCode <= 122) // a-z

    if (!isValid) return false
  }

  // If all checks pass, the string matches the pattern
  return true
}
